---
title: "OKC Thunder Technical Assessment"
author: "Max Sleek"
date: "`r Sys.Date()`"
output: html_document
---

# Packages and Data
```{r}
library(tidyverse)
shot_data <- as.data.frame(read_csv("shots_data.csv")) %>%
  mutate('shot zone' = NA, .before = fgmade)
```

# Sort Shots
```{r}
count(shot_data)
for(i in 1:504){
  if (shot_data$y[i] <= 7.8){
    if (abs(shot_data$x[i]) > 22){
      shot_data$`shot zone`[i] <- "C3"
    }else{
      shot_data$`shot zone`[i] <- "2PT"
    }
  }else{
    if(shot_data$y[i] > sqrt(564.0625 - (shot_data$x[i])^2)){
      shot_data$`shot zone`[i] <- "NC3"
    }else{
      shot_data$`shot zone`[i] <- "2PT"
    }
    if(abs(shot_data$x[i]) > 22){
      shot_data$`shot zone`[i] <- "NC3"
    }
  }
}
```

# **Rough** Plot to Check Values
```{r}
curve <- function(x) 
  sqrt(564.0625 - (x)^2)
ggplot(data=shot_data) +
  geom_point(aes(x = x, y = y, color = `shot zone`)) +
  stat_function(fun = curve)
# Note: Normally, the curve would be displayed between -22 and 22 on the x axis to represent where the arc becomes a vertical line. However, to save time, I plotted the whole curve here.
```

# Team A Analysis
```{r}
# EFG Function
efg <- function(fgm, threes_made, fga)
  (fgm + 0.5*threes_made)/(fga)

#Subset
team_a <- subset(shot_data, subset = team == "Team A")

#Percent of shots that were 2PTs: 69.3% 
team_a_2PT <- filter(team_a, `shot zone` == "2PT")
count(team_a_2PT)/count(team_a)

#Percent of shots that were NC3s: 24.3% 
team_a_NC3 <- filter(team_a, `shot zone` == "NC3")
count(team_a_NC3)/count(team_a)

#Percent of shots that were 2PTs: 6.4% 
team_a_C3 <- filter(team_a, `shot zone` == "C3")
count(team_a_C3)/count(team_a)

#EFG% on 2PTs: ~49.0%
efg(count(filter(team_a_2PT, `fgmade` == 1)), 0, count(team_a_2PT))

#EFG% on NC3s: ~46.3%
efg(count(filter(team_a_NC3, `fgmade` == 1)), count(filter(team_a_NC3, `fgmade` == 1)), count(team_a_NC3))

#EFG% on C3s: 75%
efg(count(filter(team_a_C3, `fgmade` == 1)), count(filter(team_a_C3, `fgmade` == 1)), count(team_a_C3))

#Total EFG%: 50%
efg(count(filter(team_a, `fgmade` == 1)), count(filter(team_a, `fgmade` == 1, `shot zone` != "2PT")), count(team_a))
```

# Team B Analysis
```{r}
#Subset
team_b <- subset(shot_data, subset = team == "Team B")

#Percent of shots that were 2PTs: 67.4% 
team_b_2PT <- filter(team_b, `shot zone` == "2PT")
count(team_b_2PT)/count(team_b)

#Percent of shots that were NC3s: 27.6% 
team_b_NC3 <- filter(team_b, `shot zone` == "NC3")
count(team_b_NC3)/count(team_b)

#Percent of shots that were 2PTs: 4.9% 
team_b_C3 <- filter(team_b, `shot zone` == "C3")
count(team_b_C3)/count(team_b)

#EFG% on 2PTs: ~44.3%
efg(count(filter(team_b_2PT, `fgmade` == 1)), 0, count(team_b_2PT))

#EFG% on NC3s: ~50.8%
efg(count(filter(team_b_NC3, `fgmade` == 1)), count(filter(team_b_NC3, `fgmade` == 1)), count(team_b_NC3))

#EFG% on C3s: ~54.5%
efg(count(filter(team_b_C3, `fgmade` == 1)), count(filter(team_b_C3, `fgmade` == 1)), count(team_b_C3))

#Total EFG%: ~46.6%
efg(count(filter(team_b, `fgmade` == 1)), count(filter(team_b, `fgmade` == 1, `shot zone` != "2PT")), count(team_b))
```